refactor(jakarta): migrate from javax to jakarta packages for Spring Boot 3 compatibility Addressed build failure by replacing jakarta with javax. This issue arises as Spring Boot 3 now relies on Jakarta packages instead of javax.
```
kayenta/kayenta-core/src/main/java/com/netflix/kayenta/events/CanaryExecutionCompletedEvent.java:19: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
                                   ^
kayenta/kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryExecutionStatusResponse.java:20: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
                                   ^
kayenta/kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryConfig.java:22: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
                                   ^
kayenta/kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryExecutionRequest.java:23: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
                                   ^
kayenta/kayenta-core/src/main/java/com/netflix/kayenta/canary/CanaryScopePair.java:18: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;

                                   ^
* What went wrong:
Execution failed for task ':kayenta-core:compileJava'.
> Could not resolve all files for configuration ':kayenta-core:compileClasspath'.
   > Could not find javax.validation:validation-api:.
     Required by:
         project :kayenta-core

```

Reference Links:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee